2024-04-11 15:44:19,503 - INFO -   File "C:\Users\brend\AppData\Local\Programs\Python\Python36\lib\site-packages\trixi\experiment\experiment.py", line 89, in run
    self.train(epoch=self._epoch_idx)

  File "C:\Users\brend\eICU\TPC-LoS-prediction\models\experiment_template.py", line 110, in train
    y_hat_los, y_hat_mort = self.model(padded, diagnoses, flat)

  File "C:\Users\brend\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)

  File "C:\Users\brend\eICU\TPC-LoS-prediction\models\tpc_model.py", line 596, in forward
    **kwargs)

  File "C:\Users\brend\eICU\TPC-LoS-prediction\models\tpc_model.py", line 444, in temp_pointwise
    next_X = X_combined.view(B, (point_skip.shape[1] + point_size) * (1 + temp_kernels), T)  # B * ((F + Zt + point_size) * (1 + temp_kernels)) * T

2024-04-11 15:44:19,503 - INFO - RuntimeError("view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.",)
